// =================================================
// Autogenerated from Unify 3.0.4, do not edit directly.
// =================================================

#import "LocationInfoModel.h"

@interface LocationInfoModel ()


@end

@implementation LocationInfoModel

+ (NSArray<NSObject*>*)modelList:(NSArray<NSDictionary<NSObject*, NSObject*>*>*)list {
    if ((NSNull *)list == [NSNull null]) return nil;
    NSMutableArray *models = NSMutableArray.new;
    for (NSDictionary *item in list) {
        id obj = [[self class] fromMap:item];
        [models addObject:obj];
    }
    if (models.count==0) return nil;
    return models;
}

+ (NSArray<NSObject*>*)dicList:(NSArray<NSObject*>*)list {
    if ((NSNull *)list == [NSNull null]) return nil;
    NSMutableArray *dicList = NSMutableArray.new;
    for (id item in list) {
        NSDictionary *dic = [item toMap];
        [dicList addObject:dic];
    }
    return dicList;
}

+ (id)wrapNil:(id)value {
    return (value == nil) || ((NSNull *)value == [NSNull null]) || [value isEqual:@"<null>"]? nil : value;
}

+ (LocationInfoModel*)fromMap:(NSDictionary<NSString*, NSObject*>*)dict {
    if ((NSNull *)dict == [NSNull null]) return nil;
    LocationInfoModel* result = [[LocationInfoModel alloc] init];
    result.lat = [self wrapNil:dict[@"lat"]];
    result.lng = [self wrapNil:dict[@"lng"]];
    return result;
}

- (NSDictionary<NSString*, NSObject*>*)toMap {
    return [NSDictionary dictionaryWithObjectsAndKeys:
        (self.lat ? self.lat : [NSNull null]), @"lat",
        (self.lng ? self.lng : [NSNull null]), @"lng",
        nil];
}

@end
