// =================================================
// Autogenerated from Unify 3.0.4, do not edit directly.
// =================================================

#import <Foundation/Foundation.h>
#import "UFUniCallbackDispatcher.h"

@protocol FlutterBinaryMessenger;
@class FlutterError;
@class LocationInfoModel;

NS_ASSUME_NONNULL_BEGIN

@interface OnDoCallbackAction0Callback : NSObject

@property(nonatomic, copy) NSString* callbackName; // Origin dart type is 'String'
@property(nonatomic, weak) id<UFUniCallbackDispose> delegate; // Origin dart type is 'id'

- (void)onEvent:(LocationInfoModel*)callback;

@end

@interface OnDoCallbackAction1Callback : NSObject

@property(nonatomic, copy) NSString* callbackName; // Origin dart type is 'String'
@property(nonatomic, weak) id<UFUniCallbackDispose> delegate; // Origin dart type is 'id'

- (void)onEvent:(NSString*)callback;

@end

/*
 Call flow direction : dart -> native
*/
@protocol UniCallbackTestService<UFUniCallbackDispose>


/*
  更新定位信息
*/
- (void)doCallbackAction0:(OnDoCallbackAction0Callback*)callback error:(FlutterError *_Nullable *_Nonnull)error;
- (void)doCallbackAction1:(OnDoCallbackAction1Callback*)callback error:(FlutterError *_Nullable *_Nonnull)error;

@end

extern void UniCallbackTestServiceSetup(id<FlutterBinaryMessenger> binaryMessenger, id<UniCallbackTestService> api);

NS_ASSUME_NONNULL_END
