// =================================================
// Autogenerated from Unify, do not edit directly.
// =================================================

package com.didi.hello_uni_foundation;

import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.util.ArrayList;
import com.didi.hello_uni_foundation.uniapi.UniModel;

/*
  设备信息 实体类
*/
public class DeviceInfoModel extends UniModel {
    private String osVersion; // 系统版本
    private String memory; // 内存信息
    private String plaform; // 手机型号

    public String getOsVersion() { return osVersion; }

    public void setOsVersion(String osVersion) { this.osVersion = osVersion; }

    public String getMemory() { return memory; }

    public void setMemory(String memory) { this.memory = memory; }

    public String getPlaform() { return plaform; }

    public void setPlaform(String plaform) { this.plaform = plaform; }


    @Override
    public Map<String, Object> toMap() {
        Map<String, Object> result = new HashMap<>();
        result.put("osVersion", osVersion);
        result.put("memory", memory);
        result.put("plaform", plaform);
        return result;
    }

    public static DeviceInfoModel fromMap(Map<String, Object> map) {
        DeviceInfoModel result = new DeviceInfoModel();
        result.osVersion = map.containsKey("osVersion") && map.get("osVersion") != null ? (String) map.get("osVersion") : "";
        result.memory = map.containsKey("memory") && map.get("memory") != null ? (String) map.get("memory") : "";
        result.plaform = map.containsKey("plaform") && map.get("plaform") != null ? (String) map.get("plaform") : "";
        return result;
    }

}
