// =================================================
// Autogenerated from Unify, do not edit directly.
// =================================================

package com.didi.hello_uni_foundation;

import java.util.List;
import java.util.Map;
import java.util.HashMap;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.StandardMessageCodec;
import com.didi.hello_uni_foundation.DeviceInfoModel;

public interface DeviceInfoService {

    interface Result<T> {
        void success(T result);

    }

    /*
      获取设备信息
    */
    void getDeviceInfo(Result<DeviceInfoModel> result);

}
