// =================================================
// Autogenerated from Unify 3.0.4, do not edit directly.
// =================================================

import 'package:flutter/services.dart';

import 'location_info_model.dart';

/// Call flow direction : native -> dart
abstract class LocationInfoService {

    void updateLocationInfo(LocationInfoModel model);

    static void setup(LocationInfoService impl) {
        {
            const BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>('com.didi.flutter.uni_api.LocationInfoService.updateLocationInfo', StandardMessageCodec());
            channel.setMessageHandler((Object? message) async {
                if (message == null) return null;
                Map<Object?, Object?> wrapped = message as Map<Object?, Object?>;
                impl.updateLocationInfo(LocationInfoModel.decode(wrapped['model']!));
            });
        }
    }
}
