// =================================================
// Autogenerated from Unify 3.0.4, do not edit directly.
// =================================================

package com.example.unicallback_demo;

public class UFUniCallback {
    public String callbackName;
    public UFUniCallbackDispose disposeDelegate;

    public UFUniCallback(String callbackName, UFUniCallbackDispose disposeDelegate) {
        this.callbackName = callbackName;
        this.disposeDelegate = disposeDelegate;
    }
}

