// =================================================
// Autogenerated from Unify 3.0.2, do not edit directly.
// =================================================

package com.example.unicallback_demo;

import java.util.List;
import java.util.Map;
import java.util.HashMap;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.StandardMessageCodec;
import com.example.unicallback_demo.LocationInfoModel;

/*
 Call flow direction : dart -> native
*/
public interface UniCallbackTestService {


    class OnDoCallbackAction0Callback {
        public String callbackName;
        private BinaryMessenger messenger;


        public OnDoCallbackAction0Callback(BinaryMessenger messenger, String callbackName) {
            this.messenger = messenger;
            this.callbackName = callbackName;
        }

        public void onEvent(LocationInfoModel event) {
            Map<String, Object> message = new HashMap<>();
            message.put("callbackName", callbackName);
            message.put("data", event.toMap());
            new BasicMessageChannel<>(messenger, "com.didi.flutter.uni_api.UniCallbackManager.callback_channel.uf", StandardMessageCodec.INSTANCE).send(message);
        }
    }
    class OnDoCallbackAction1Callback {
        public String callbackName;
        private BinaryMessenger messenger;


        public OnDoCallbackAction1Callback(BinaryMessenger messenger, String callbackName) {
            this.messenger = messenger;
            this.callbackName = callbackName;
        }

        public void onEvent(String event) {
            Map<String, Object> message = new HashMap<>();
            message.put("callbackName", callbackName);
            message.put("data", event);
            new BasicMessageChannel<>(messenger, "com.didi.flutter.uni_api.UniCallbackManager.callback_channel.uf", StandardMessageCodec.INSTANCE).send(message);
        }
    }
    /*
      更新定位信息
    */
    void doCallbackAction0(OnDoCallbackAction0Callback callback);

    void doCallbackAction1(OnDoCallbackAction1Callback callback);

}
