// =================================================
// Autogenerated from Unify 3.0.2, do not edit directly.
// =================================================

#import "DeviceInfoModel.h"

@interface DeviceInfoModel ()


@end

@implementation DeviceInfoModel

+ (NSArray<NSObject*>*)modelList:(NSArray<NSDictionary<NSObject*, NSObject*>*>*)list {
    if ((NSNull *)list == [NSNull null]) return nil;
    NSMutableArray *models = NSMutableArray.new;
    for (NSDictionary *item in list) {
        id obj = [[self class] fromMap:item];
        [models addObject:obj];
    }
    if (models.count==0) return nil;
    return models;
}

+ (NSArray<NSObject*>*)dicList:(NSArray<NSObject*>*)list {
    if ((NSNull *)list == [NSNull null]) return nil;
    NSMutableArray *dicList = NSMutableArray.new;
    for (id item in list) {
        NSDictionary *dic = [item toMap];
        [dicList addObject:dic];
    }
    return dicList;
}

+ (id)wrapNil:(id)value {
    return (value == nil) || ((NSNull *)value == [NSNull null]) || [value isEqual:@"<null>"]? nil : value;
}

+ (DeviceInfoModel*)fromMap:(NSDictionary<NSString*, NSObject*>*)dict {
    if ((NSNull *)dict == [NSNull null]) return nil;
    DeviceInfoModel* result = [[DeviceInfoModel alloc] init];
    result.osVersion = [self wrapNil:dict[@"osVersion"]];
    result.memory = [self wrapNil:dict[@"memory"]];
    result.plaform = [self wrapNil:dict[@"plaform"]];
    return result;
}

- (NSDictionary<NSString*, NSObject*>*)toMap {
    return [NSDictionary dictionaryWithObjectsAndKeys:
        (self.osVersion ? self.osVersion : [NSNull null]), @"osVersion",
        (self.memory ? self.memory : [NSNull null]), @"memory",
        (self.plaform ? self.plaform : [NSNull null]), @"plaform",
        nil];
}

@end
