// =================================================
// Autogenerated from Unify 3.0.4, do not edit directly.
// =================================================

#import <Foundation/Foundation.h>
#import <Flutter/Flutter.h>
NS_ASSUME_NONNULL_BEGIN

@protocol UDUniCallbackDispose
@required
- (void)disposeCallback:(id)params;
@end

@interface UDUniCallbackDispatcher : NSObject
+ (void)init:(NSObject<FlutterBinaryMessenger>* _Nonnull)binaryMessenger;
+ (void)registe:(NSString * _Nonnull)name callback:(id _Nonnull)subscriber;
@end

NS_ASSUME_NONNULL_END
