// =================================================
// Autogenerated from Unify 3.0.0, do not edit directly.
// =================================================

package com.example.uninativemodule_demo;

import java.util.List;
import java.util.Map;
import java.util.HashMap;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.StandardMessageCodec;
import com.example.uninativemodule_demo.DeviceInfoModel;

/*
 Call flow direction : dart -> native
*/
public interface DeviceInfoService {

    interface Result<T> {
        void success(T result);

    }

    /*
      获取设备信息
    */
    void getDeviceInfo(Result<DeviceInfoModel> result);

}
