import 'package:unify_flutter/ast/basic/ast_variable.dart';
import 'package:unify_flutter/ast/uniapi/ast_method.dart';
import 'package:unify_flutter/utils/extension/ast_extension.dart';

extension MethodExtension on Method {
  /// Check if the user-declared interface has the RequiredMessager annotation.
  bool get hasMessagerAnno =>
      lastArgument == null ? false : parameters.last.type.hasMessagerAnno();

  /// Return the real parameters of the user-declared Dart interface.
  List<Variable> get realDartMethodParams => hasMessagerAnno
      ? parameters
          .take(parameters.length - 1)
          .toList() // If the method has the RequiredMessager annotation, remove the last parameter.
      : parameters;

  /// Return the last parameter from the 'Method' parameter list generated by Unify's Analyzer.
  Variable? get lastArgument => parameters.lastOrNull;
}
