// =================================================
// Autogenerated from Unify 3.0.4, do not edit directly.
// =================================================

package com.example.unifluttermodule_demo;

import android.util.Log;

import java.util.HashMap;
import java.util.Map;

import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.StandardMessageCodec;

public class UFUniCallbackDispatcher {
    public static Map<String, UFUniCallback> uniCallbackCache = new HashMap<>();

    private static boolean isInit = false;

    public static void init(BinaryMessenger binaryMessenger) {
        if (!isInit) {
            BasicMessageChannel<Object> channel =
                    new BasicMessageChannel<>(binaryMessenger, "com.didi.flutter.uni_api.UniCallbackManager.callback_channel.dispose.uf", new StandardMessageCodec());

            channel.setMessageHandler((message, reply) -> {
                Map<String, Object> msg = (Map<String, Object>) message;
                String uniCallbackName = (String) msg.get("callback");
                UFUniCallback uniCallback = uniCallbackCache.get(uniCallbackName);
                uniCallback.disposeDelegate.disposeCallback(uniCallback);
                uniCallbackCache.remove(uniCallbackName);
            });
            isInit = true;
        }
    }

    public static void registerCallback(String name, UFUniCallback uniCallback) {
        uniCallbackCache.put(name, uniCallback);
    }
}

